Updated daily script for move to gerris.dalembert

diff --git a/tools/daily b/tools/daily
--- a/tools/daily
+++ b/tools/daily
@@ -5,13 +5,22 @@
 # Gerris tests
 wdir=$HOME/local/src/gerris-tests
 
+if test -f $wdir/lock; then
+    echo "$wdir/lock found!"
+    exit 1
+else
+    touch $wdir/lock
+fi
+
 gerris=gerris-stable
 gfsview=gfsview-stable
 gts=gts-mainline
 
-darcs_gts=$HOME/local/src/darcs/gts
-darcs_gerris=popinet@patch-tag.com:/r/popinet
-darcs_gfsview=popinet@patch-tag.com:/r/popinet
+darcs_gts=http://gts.sf.net/darcs
+gerris_devel=popinet@patch-tag.com:/r/popinet/gerris-devel
+gerris_stable=/var/www/darcs/gerris-stable
+gfsview_devel=popinet@patch-tag.com:/r/popinet/gfsview-devel
+gfsview_stable=/var/www/darcs/gfsview-stable
 
 gtsweb=popinet,gts@web.sourceforge.net:/home/groups/g/gt/gts/htdocs
 gerrisweb=popinet,gfs@web.sourceforge.net:/home/groups/g/gf/gfs/htdocs
@@ -19,21 +28,11 @@ localgerrisweb=/var/www/gerris
 
 archive_key=$HOME/.gnupg/popinet_key.asc
 
-export https_proxy=http://www-proxy.niwa.co.nz:80
-
-export PATH=$wdir/local/bin:$PATH:/usr/local/bin
-export LD_LIBRARY_PATH=$wdir/local/lib:$LD_LIBRARY_PATH:/usr/local/lib
-export PKG_CONFIG_PATH=$wdir/local/lib/pkgconfig:$PKG_CONFIG_PATH
+export PATH=$HOME/local/bin:/usr/local/bin:$PATH
+export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH:/usr/local/lib
+export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
 export GFS_TERRAIN_PATH=$HOME/terrain:.
 ulimit -c unlimited
-
-# debian build looks for shlibs and symbols file in locally compiled
-# libgts-snapshot debian packages:
-export DEB_DH_SHLIBDEPS_ARGS_ALL="-- -S$wdir/$gts/debian/libgts-snapshot -S$wdir/$gerris/debian/gerris-snapshot"
-
-# kill all running rsync processes. Assumes the only ones would be
-# hanging rsync from previous calls of this script!!
-killall rsync 2> /dev/null
 
 # Formats log files
 redate()
@@ -52,8 +51,8 @@ redate()
 	Month["Nov"] = 11
 	Month["Dec"] = 12
 	date=""
-    }{
-	if ($5 == "NZST" || $5 == "NZDT") {
+    }
+    /.* [0-9][0-9]:[0-9][0-9]:[0-9][0-9] .*/{
 	    year=$6
 	    day=$3
 	    month=$2
@@ -69,12 +68,11 @@ redate()
 	    else
 		noprint = 1;
 	    while (getline && NF > 0) {
-		if (!noprint)
+		if (!noprint && $1 != "Ignore-this:")
 		    print $0;
 	    }
 	    if (!noprint)
 		print;
-	}
     }' | sed 's/@/ at /g'
 }
 
@@ -98,9 +96,11 @@ darcs_upgrade()
 		awk 'BEGIN{RS=" ";FS="="} {
                 if ($1 == "date") 
                   printf ("%s-%s-%s", substr($2,2,4), substr($2,6,2), substr($2,8,2));
-               }' > $package"_current" ) && \
-		   darcs tag $(cat $package"_current") && \
-		   darcs push -a --no-set-default $1 ; then :
+               }' > $package"_current" ) \
+		   && \
+		   darcs tag -A Release $(cat $package"_current") && \
+		   darcs push -a --no-set-default $1 ;
+	    then :
 	    else
 		rm -f $changes
 		return 1;
@@ -113,13 +113,38 @@ darcs_upgrade()
     rm -f $changes
 }
 
+exit_cleanup()
+{
+    rm -f $wdir/lock
+    exit $1
+}
+
+darcs_update()
+{
+    f=`mktemp`
+    if darcs pull -a $1 > $f 2>&1; then
+	if grep "No remote changes to pull in" $f > /dev/null; then
+	    status=0
+	else
+	    status=1
+	fi
+	rm -f $f
+	return $status;
+    else
+	cat $f
+	rm -f $f
+	exit_cleanup 1
+    fi
+}
+
 build_gts=false
-if ( cd $wdir/$gts && make -k clean && \
-    ( darcs pull -a $darcs_gts/gts-devel | grep "No remote changes to pull in" ) ) > /dev/null 2>&1 ; then
+cd $wdir/$gts
+( make -k distclean ) > /dev/null 2>&1
+if darcs_update $darcs_gts/gts-devel; then
     gts_changed=false
 else
     gts_changed=true
-    if ( cd $wdir/$gts && sh autogen.sh --prefix=$wdir/local && make -k && make -k install ) \
+    if ( cd $wdir/$gts && sh autogen.sh --prefix=$HOME/local && make -k && make -k install ) \
        > $wdir/build 2>&1 ; then :
 	build_gts=true
     else
@@ -127,13 +152,14 @@ else
         echo ============ $wdir/$gts: build failed ============
 	echo
 	cat $wdir/build
-	exit 1
+	exit_cleanup 1
     fi
 fi
 
 build_gerris=false
-if ( cd $wdir/$gerris && make -k clean && \
-    ( darcs pull -a $darcs_gerris/gerris-devel | grep "No remote changes to pull in" ) ) > /dev/null 2>&1 ; then
+cd $wdir/$gerris
+( make -k distclean ) > /dev/null 2>&1
+if darcs_update $gerris_devel; then
     gerris_changed=false
     if $build_gts ; then
 	build_gerris=true
@@ -143,20 +169,22 @@ else
     build_gerris=true
 fi
 if $build_gerris ; then
-    if ( cd $wdir/$gerris && sh autogen.sh --prefix=$wdir/local && make -k && make -k install ) \
+    if ( cd $wdir/$gerris && sh autogen.sh --prefix=$HOME/local --enable-agmg && \
+	 make -k && make -k install ) \
        > $wdir/build 2>&1 ; then :
     else
 	echo
         echo ============ $wdir/$gerris: build failed ============
 	echo
 	cat $wdir/build
-	exit 1
+	exit_cleanup 1
     fi
 fi
 
 build_gfsview=false
-if ( cd $wdir/$gfsview && make -k clean && \
-    ( darcs pull -a $darcs_gfsview/gfsview-devel | grep "No remote changes to pull in" ) ) > /dev/null 2>&1 ; then :
+cd $wdir/$gfsview
+( make -k distclean ) > /dev/null 2>&1
+if darcs_update $gfsview_devel; then :
     gfsview_changed=false
     if $build_gerris ; then
 	build_gfsview=true
@@ -166,26 +194,27 @@ else
     build_gfsview=true
 fi
 if $build_gfsview ; then
-    if ( cd $wdir/$gfsview && sh autogen.sh --prefix=$wdir/local && make -k && make -k install ) \
+    if ( cd $wdir/$gfsview && sh autogen.sh --prefix=$HOME/local && make -k && make -k install ) \
        > $wdir/build 2>&1 ; then :
     else
 	echo
         echo ============ $wdir/$gfsview: build failed ============
 	echo
 	cat $wdir/build
-	exit 1
+	exit_cleanup 1
     fi
 fi
 
 if ( $build_gerris || $build_gfsview ) ; then
-   if ( cd $wdir/$gerris && make -k check ) > $wdir/check 2>&1 ; then :
+   if ( cd $wdir/$gerris && sh autogen.sh --prefix=$HOME/local --enable-agmg && \
+       make -j8 -k check ) > $wdir/check 2>&1 ; then :
    else
        check=1
    fi
-   if ( cd $wdir/$gerris/test && make -k tests.tar.gz && \
+   if ( cd $wdir/$gerris/test && make -k publish && \
         cd $wdir/$gerris/doc/tutorial && make -k tutorial.pdf tutorial.tar.gz && \
-        cd $wdir/$gerris/doc/examples && make -k examples.tar.gz && \
-        cd $wdir/$gerris/doc && make -k templates sgml html ) > $wdir/tests 2>&1 ; then :
+        cd $wdir/$gerris/doc/examples && make -k publish && \
+        cd $wdir/$gerris/doc && make -k publish ) > $wdir/tests 2>&1 ; then :
    else
        tests=1
    fi
@@ -196,6 +225,8 @@ if ( $build_gerris || $build_gfsview ) ; then
 	   echo file://$wdir/$gerris/test/tests/index.html
        fi
        echo
+       cat $wdir/$gerris/test/test-suite.log
+       cat $wdir/$gerris/doc/examples/test-suite.log
        cat $wdir/check
    fi
    if test $tests; then
@@ -206,54 +237,54 @@ if ( $build_gerris || $build_gfsview ) ; then
    fi
    if test -z "$check" && test -z "$tests"; then
        if ( cd $wdir/$gts && darcs_upgrade $darcs_gts/$gts gts && \
-	    cd $wdir/$gerris && darcs_upgrade $darcs_gerris/$gerris gerris && \
-	    cd $wdir/$gfsview && darcs_upgrade $darcs_gfsview/$gfsview gfsview ) \
+	    cd $wdir/$gerris && darcs_upgrade $gerris_stable gerris && \
+	    cd $wdir/$gfsview && darcs_upgrade $gfsview_stable gfsview ) \
 	   > $wdir/darcs 2>&1 ; then
 	   gts_snapshot=true
-	   if $gts_changed ; then
-	       if ( darcs2dist gts $darcs_gts/$gts $gtsweb && \
-                    cd $wdir/$gts && make ChangeLog buildservice-snapshot ) \
-               > $wdir/snapshot 2>&1 ; then :
-	       else
-		   echo
-		   echo ============ $wdir: GTS snapshot failed ============
-		   echo
-		   cat $wdir/snapshot
-		   gts_snapshot=false
-	       fi
-	   fi
+	   # if $gts_changed ; then
+	   #     if ( darcs2dist gts $darcs_gts/$gts $gtsweb && \
+           #          cd $wdir/$gts && make ChangeLog buildservice-snapshot ) \
+           #     > $wdir/snapshot 2>&1 ; then :
+	   #     else
+	   # 	   echo
+	   # 	   echo ============ $wdir: GTS snapshot failed ============
+	   # 	   echo
+	   # 	   cat $wdir/snapshot
+	   # 	   gts_snapshot=false
+	   #     fi
+	   # fi
 	   gerris_snapshot=true
 	   if $gerris_changed && $gts_snapshot ; then
-	       if ( darcs2dist gerris $darcs_gerris/$gerris $gerrisweb ) \
+	       if ( darcs2dist gerris $gerris_stable $localgerrisweb ) \
                > $wdir/snapshot 2>&1 ; then :
 	       else
-		   echo
-		   echo ============ $wdir: Gerris snapshot failed ============
-		   echo
-		   cat $wdir/snapshot
-		   gerris_snapshot=false
+	   	   echo
+	   	   echo ============ $wdir: Gerris snapshot failed ============
+	   	   echo
+	   	   cat $wdir/snapshot
+	   	   gerris_snapshot=false
 	       fi
 	   fi
 	   gerris_debian=true
            if $gts_snapshot && ( $gts_changed || $gerris_changed ) ; then
 	       if ( cd $wdir/$gerris && make ChangeLog buildservice-snapshot ) \
-		   > $wdir/debian 2>&1 ; then :
+	   	   > $wdir/debian 2>&1 ; then :
 	       else
-		   echo
-		   echo ============ $wdir: Gerris debian failed ============
-		   echo
-		   cat $wdir/debian
-		   gerris_debian=false
+	   	   echo
+	   	   echo ============ $wdir: Gerris buildservice failed ============
+	   	   echo
+	   	   cat $wdir/debian
+	   	   gerris_debian=false
 	       fi
 	   fi
 	   if $gfsview_changed && $gerris_snapshot ; then
-	       if ( darcs2dist gfsview $darcs_gfsview/$gfsview $gerrisweb ) \
+	       if ( darcs2dist gfsview $gfsview_stable $localgerrisweb ) \
                > $wdir/snapshot 2>&1 ; then :
 	       else
-		   echo
-		   echo ============ $wdir: GfsView snapshot failed ============
-		   echo
-		   cat $wdir/snapshot
+	   	   echo
+	   	   echo ============ $wdir: GfsView snapshot failed ============
+	   	   echo
+	   	   cat $wdir/snapshot
 	       fi
 	   fi
 	   gfsview_debian=true
@@ -262,11 +293,11 @@ if ( $build_gerris || $build_gfsview ) ; then
 	       if ( cd $wdir/$gfsview && make ChangeLog buildservice-snapshot ) \
                > $wdir/debian 2>&1 ; then :
 	       else
-		   echo
-		   echo ============ $wdir: GfsView debian failed ============
-		   echo
-		   cat $wdir/debian
-		   gfsview_debian=false
+	   	   echo
+	   	   echo ============ $wdir: GfsView buildservice failed ============
+	   	   echo
+	   	   cat $wdir/debian
+	   	   gfsview_debian=false
 	       fi
 	   fi
        else
@@ -277,25 +308,21 @@ if ( $build_gerris || $build_gfsview ) ; then
        fi
    fi
    if test -z "$tests"; then
-       if ( cd $wdir/$gerris/test && \
-           rm -r -f $localgerrisweb/tests/* && \
-           cp tests.tar.gz $localgerrisweb/tests/ && \
-	   cd $localgerrisweb/tests/ && \
-	   tar xzf tests.tar.gz && rm -f tests.tar.gz && \
-	   cd $wdir/$gerris/doc/examples && \
-           rm -r -f $HOME/local/src/gerris-www/publish/examples/* && \
-           cp examples.tar.gz $HOME/local/src/gerris-www/publish/examples/ && \
-	   cd $HOME/local/src/gerris-www/publish/examples/ && \
-	   tar xzf examples.tar.gz && rm -f examples.tar.gz && \
-	   cd $wdir/$gts && rm -f ChangeLog && make ChangeLog && \
-	   redate < ChangeLog | source-highlight -f html -s changelog -d -T "GTS ChangeLog" > $HOME/local/src/gts-www/publish/ChangeLog.html && \
+       if ( 
+           # cd $wdir/$gts && rm -f ChangeLog && make ChangeLog && \
+	   # redate < ChangeLog | source-highlight -f html -s changelog -d -T "GTS ChangeLog" > $HOME/local/src/gts-www/publish/ChangeLog.html && \
 	   cd $wdir/$gerris && rm -f ChangeLog && make ChangeLog && \
 	   redate < ChangeLog | source-highlight -f html -s changelog -d -T "Gerris ChangeLog" > $localgerrisweb/gerris-ChangeLog.html && \
-	   cp -f $wdir/$gerris/doc/examples/gfs.php $localgerrisweb/mediawiki-1.6.6/extensions/SyntaxHighlight_GeSHi/geshi/geshi/ && \
+	   # cp -f $wdir/$gerris/doc/examples/gfs.php $localgerrisweb/mediawiki-1.6.6/extensions/SyntaxHighlight_GeSHi/geshi/geshi/ && \
 	   cd $wdir/$gfsview && rm -f ChangeLog && make ChangeLog && \
 	   redate < ChangeLog | source-highlight -f html -s changelog -d -T "GfsView ChangeLog" > $localgerrisweb/gfsview-ChangeLog.html && \
-	   cd $HOME/local/src/gerris-www && make publish_local sync && \
-	   cd $HOME/local/src/gts-www && make sync ) > $wdir/www 2>&1 ; then :
+	   scp popinet,gfs@web.sf.net:/home/groups/g/gf/gfs/htdocs/wiki/LocalSettings.php . && \
+	   touch LocalSettings.php && \
+	   scp LocalSettings.php popinet,gfs@web.sf.net:/home/groups/g/gf/gfs/htdocs/wiki
+	   # && \
+	   # cd $HOME/local/src/gerris-www && make publish_local sync && \
+	   # cd $HOME/local/src/gts-www && make sync 
+	   ) > $wdir/www 2>&1 ; then :
        else
 	   echo
 	   echo ============ $wdir: www failed ============
@@ -304,3 +331,11 @@ if ( $build_gerris || $build_gfsview ) ; then
        fi
    fi
 fi
+
+# synchronize on sourceforge
+sfweb=popinet,gfs@web.sourceforge.net:/home/groups/g/gf/gfs/htdocs
+rsync -rl /var/www/gerris/version/ $sfweb/version
+rsync -rl /var/www/gerris/examples/examples/references/ $sfweb/examples/examples/references
+rsync -rl /var/www/gerris/tests/tests/references/ $sfweb/tests/tests/references
+
+exit_cleanup 0
